# Generated by Django 5.0.6 on 2024-06-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_alter_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='car', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
