# Generated by Django 5.0.6 on 2024-06-10 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_alter_brand_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='quantity',
        ),
    ]
