# Generated by Django 5.0.6 on 2024-06-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0002_remove_taskcategory_task'),
        ('TaskModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='Category',
            field=models.ManyToManyField(to='TaskCategory.taskcategory'),
        ),
    ]
