# Generated by Django 5.0.6 on 2024-06-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='quantity',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
