# Generated by Django 5.0.6 on 2024-06-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
