# Generated by Django 5.0.6 on 2024-06-07 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumName', models.CharField(max_length=50)),
                ('AlbumReleaseDate', models.DateTimeField(auto_now_add=True)),
                ('Rating', models.CharField(choices=[(5, '5'), (4, '4'), (1, '1'), (2, '2'), (3, '3')], default=1, max_length=1)),
                ('Albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musician')),
            ],
        ),
    ]
