# Generated by Django 5.0.6 on 2024-06-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Rating',
            field=models.CharField(choices=[(4, '4'), (3, '3'), (5, '5'), (1, '1'), (2, '2')], default=1, max_length=1),
        ),
    ]
