# Generated by Django 5.0.6 on 2024-05-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_rename_album_albummodel_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='Rating',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('4', 5)], default=1, max_length=1),
        ),
    ]
