# Generated by Django 5.0.6 on 2024-05-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_albummodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='Rating',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('4', 5)], default='1', max_length=1),
        ),
    ]
