# Generated by Django 5.0.6 on 2024-06-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_album_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Rating',
            field=models.CharField(choices=[(2, '2'), (4, '4'), (5, '5'), (1, '1'), (3, '3')], default=1, max_length=1),
        ),
    ]
