# Generated by Django 5.0.6 on 2024-05-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_albummodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='AlbumReleaseDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
