# Generated by Django 5.0.6 on 2024-05-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_alter_albummodel_albumreleasedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='AlbumReleaseDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
