# Generated by Django 5.0.6 on 2024-06-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_alter_album_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Rating',
            field=models.CharField(choices=[(3, '3'), (5, '5'), (2, '2'), (1, '1'), (4, '4')], default=1, max_length=1),
        ),
    ]
