# Generated by Django 5.0.6 on 2024-06-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_alter_album_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Rating',
            field=models.CharField(choices=[(4, 4), (5, 5), (3, 3), (2, 2), (1, 1)], default=1, max_length=1),
        ),
    ]
