# Generated by Django 5.0.6 on 2024-06-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_alter_album_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Rating',
            field=models.CharField(choices=[('2', 2), ('3', 3), ('1', 1), ('4', 4), ('5', 5)], default=1, max_length=1),
        ),
    ]
