# Generated by Django 5.0.6 on 2024-06-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0008_alter_album_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Rating',
            field=models.CharField(choices=[(5, '5'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, max_length=1),
        ),
    ]
