# Generated by Django 5.0.6 on 2024-06-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0011_alter_album_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Albums',
            new_name='Singer',
        ),
    ]
