# Generated by Django 5.0.6 on 2024-05-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_alter_musicianmodel_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
